### PR TITLE
Update

### PR DESCRIPTION
**Pull request by SamCarraro**
Fixed added prerequisites, fixed markdown problem, fixed image path of 2 example images, added land contours

### CODE REVIEW

**Comment by gcipolletta** [comment]
Dear @SamCarraro 

Thank you for your recent updates to the project! However we noticed that the markdown cells are still set to "code" (as shown in the attached image). Could you please ensure that the description cells are properly configured as "markdown" and re-compiled? 

Thanks in advance, a new pull request implementing this change would be highly appreciated.

Kind regards,
Gaia

Screenshot 2024-08-27 100238
image

**Comment by SamCarraro** [comment]
Hi @gcipolletta,

thanks for testing. For me it somehow works if I look in the jupyterlab. Would you maybe have time for a short 10min Teams meetup today, than I think we could resolve the issue faster. (https://teams.microsoft.com/l/meetup-join/19%3ameeting_MzkxZDU5MjYtYzM2Ny00NzczLTkyY2ItNTE1Mzc5NTUzY2Rm%40thread.v2/0?context=%7b%22Tid%22%3a%22733c474c-6770-4719-9d4d-617b8f59caef%22%2c%22Oid%22%3a%22acc92e8f-f310-40b1-ade7-52bd89525a0c%22%7d)

Thanks,
Samuel

**Comment by gcipolletta** [comment]
Dear @SamCarraro 

Yes indeed it is definitely an issue on Jupyter side on my user, I will clarify with CGI team separately.

Please ignore the requested task, we tested with a couple of "fresh" accounts and the issue does not persist as foreseen by your changes.

Thanks for your kind cooperation,
Gaia

**Comment by SamCarraro** [comment]
Dear @gcipolletta,

for me it worked when I stashed all local changes in the jupyterlab and reset it back to the head of the master. Before I also had some issues with my local changes.

Best regards,
Samuel

**Comment by gcipolletta** [comment]
Many thanks that's a useful suggestion!

**Pull request merged**
