### PR TITLE
DestineStreamer: updated streaming library, two jupyter notebooks and one additional image.

### PR DESCRIPTION
**Pull request by geo-bayer**
This pull request contains changes to DestineStreamer. There is a new dtelib2.py which replaces dtelib.py, two jupyter notebooks which replace the previously existing ones and an additional image to preview in one of the notebooks.

### CODE REVIEW

**Comment by gcipolletta** [comment]
Hi @geo-bayer, still experiencing conflicts that prevent to merge this contribute to the main

**Comment by geo-bayer** [comment]
Hello @gcipolletta I opened this draft to see what the conflict is, as it is a file that is deleted on our end. I didn't expect this to be reviewed already.

**Comment by gcipolletta** [comment]
Dear @geo-bayer many thanks for clarifying, no problem then let us know when the contribute is ready I can easily see if it can be merged or not

**Comment by geo-bayer** [comment]
Thank you very much @gcipolletta, I will let you know

**Pull request closed without merging**
